In [1]:
from check_matrices import *

In [2]:
n = 6
with open(f'data/{n}_qubit_top_left.data', 'rb') as reader:
    top_lefts = pickle.load(reader)

In [3]:
merged_mats = get_bottom_right_and_merge(top_lefts)
len(merged_mats)

2825

In [4]:
merged_mats[1]

(array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8),
 (1, 6),
 [0])

In [5]:
top_lefts[1]

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [6]:
test_gen = generate_top_right(np.array([[1, 0, 0, 0, 0, 0],
                                        [0, 1, 0, 0, 0, 0]], dtype=np.int8), [0, 1])

In [15]:
next(test_gen)

StopIteration: 

In [2]:
import pickle
with open('data/6_qubit_subgroups_cool.data', 'rb') as reader:
    xmatrs = pickle.load(reader)

In [4]:
xmatrs[:10]

[array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8),
 array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8),
 array([[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8),
 array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

------

In [6]:
import numpy as np
def num_of_stab_states(n):
    return 2**n * np.prod(2**np.arange(1, n+1) + 1)

In [7]:
n = 5
num_of_stab_states(n), num_of_stab_states(n) // 2**n

(2423520, 75735)

In [8]:
n = 6
num_of_stab_states(n), num_of_stab_states(n) // 2**n

(315057600, 4922775)

In [3]:
from julia import Julia
jl = Julia(sysimage='/home/lemingathon/anaconda3/bin/sys.so')

In [4]:
from julia import Base
Base.julia_cmd()

<PyCall.jlwrap `/home/lemingathon/anaconda3/bin/julia-py -Cnative -J/home/lemingathon/anaconda3/bin/sys.so -g1`>

In [5]:
from julia import Main

In [6]:
%load_ext julia.magic

Initializing Julia interpreter. This may take some time...


In [7]:
%julia using QuantumClifford

In [ ]:
symp_mats = %julia [stab_to_gf2(cliff.tab) for cliff in enumerate_cliffords(4)];
len(symp_mats)

In [11]:
from helper_functions import rref_binary

xmatrs_with_dups = []
for mat in symp_mats:
    xmatrs_with_dups.append(rref_binary(mat[:2, :]).astype(np.int8))
len(xmatrs_with_dups)

720

In [12]:
xmatrs = set()
for mat in xmatrs_with_dups:
    xmatrs = xmatrs.union({str(mat)})
len(xmatrs)

15

In [13]:
import pickle
with open('data/2_qubit_subgroups.data', 'rb') as reader:
    subgroups = pickle.load(reader)

In [17]:
print(*xmatrs, sep='\n', end='\n------------\n')
print(*subgroups, sep='\n')

[[1 0 1 0]
 [0 1 0 1]]
[[1 0 1 0]
 [0 1 0 0]]
[[1 0 0 1]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 0]]
[[0 0 1 0]
 [0 0 0 1]]
[[1 0 1 0]
 [0 0 0 1]]
[[1 0 0 1]
 [0 1 1 1]]
[[1 1 0 0]
 [0 0 1 1]]
[[0 1 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 1 0 1]]
[[1 1 0 1]
 [0 0 1 1]]
[[1 0 0 0]
 [0 1 0 0]]
[[1 0 1 1]
 [0 1 1 1]]
[[1 0 0 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]]
------------
[[0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]]
[[0 1 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 0 0 1]]
[[1 0 1 0]
 [0 0 0 1]]
[[1 1 0 0]
 [0 0 1 1]]
[[1 1 0 1]
 [0 0 1 1]]
[[1 0 0 0]
 [0 1 0 0]]
[[1 0 0 0]
 [0 1 0 1]]
[[1 0 0 1]
 [0 1 1 0]]
[[1 0 0 1]
 [0 1 1 1]]
[[1 0 1 0]
 [0 1 0 0]]
[[1 0 1 0]
 [0 1 0 1]]
[[1 0 1 1]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 1]]


In [45]:
Lambda = np.block([[np.zeros((n, n)), np.eye(n)], [np.eye(n), np.zeros((n, n))]]).astype(np.int8)
Lambda

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]], dtype=int8)