In [1]:
import numpy as np
def num_of_stab_states(n):
    return 2**n * np.prod(2**np.arange(1, n+1) + 1)

In [2]:
n = 6
num_of_stab_states(n), num_of_stab_states(n) // 2**n

(315057600, 4922775)

In [3]:
from julia import Julia
jl = Julia(sysimage='/home/lemingathon/anaconda3/bin/sys.so')

In [4]:
from julia import Base
Base.julia_cmd()

<PyCall.jlwrap `/home/lemingathon/anaconda3/bin/julia-py -Cnative -J/home/lemingathon/anaconda3/bin/sys.so -g1`>

In [5]:
from julia import Main

In [6]:
%load_ext julia.magic

Initializing Julia interpreter. This may take some time...


In [7]:
%julia using QuantumClifford

In [ ]:
symp_mats = %julia [stab_to_gf2(cliff.tab) for cliff in enumerate_cliffords(4)];
len(symp_mats)

In [11]:
from helper_functions import rref_binary

xmatrs_with_dups = []
for mat in symp_mats:
    xmatrs_with_dups.append(rref_binary(mat[:2, :], False).astype(np.int8))
len(xmatrs_with_dups)

720

In [12]:
xmatrs = set()
for mat in xmatrs_with_dups:
    xmatrs = xmatrs.union({str(mat)})
len(xmatrs)

15

In [13]:
import pickle
with open('data/2_qubit_subgroups.data', 'rb') as reader:
    subgroups = pickle.load(reader)

In [17]:
print(*xmatrs, sep='\n', end='\n------------\n')
print(*subgroups, sep='\n')

[[1 0 1 0]
 [0 1 0 1]]
[[1 0 1 0]
 [0 1 0 0]]
[[1 0 0 1]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 0]]
[[0 0 1 0]
 [0 0 0 1]]
[[1 0 1 0]
 [0 0 0 1]]
[[1 0 0 1]
 [0 1 1 1]]
[[1 1 0 0]
 [0 0 1 1]]
[[0 1 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 1 0 1]]
[[1 1 0 1]
 [0 0 1 1]]
[[1 0 0 0]
 [0 1 0 0]]
[[1 0 1 1]
 [0 1 1 1]]
[[1 0 0 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]]
------------
[[0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]]
[[0 1 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 0 0 1]]
[[1 0 1 0]
 [0 0 0 1]]
[[1 1 0 0]
 [0 0 1 1]]
[[1 1 0 1]
 [0 0 1 1]]
[[1 0 0 0]
 [0 1 0 0]]
[[1 0 0 0]
 [0 1 0 1]]
[[1 0 0 1]
 [0 1 1 0]]
[[1 0 0 1]
 [0 1 1 1]]
[[1 0 1 0]
 [0 1 0 0]]
[[1 0 1 0]
 [0 1 0 1]]
[[1 0 1 1]
 [0 1 1 0]]
[[1 0 1 1]
 [0 1 1 1]]


In [45]:
Lambda = np.block([[np.zeros((n, n)), np.eye(n)], [np.eye(n), np.zeros((n, n))]]).astype(np.int8)
Lambda

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]], dtype=int8)

In [47]:
(sm @ Lambda @ sm.T) % 2

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]], dtype=int8)

In [49]:
sm_trunc = sm[:2, :]
(sm_trunc @ Lambda @ sm_trunc.T) % 2

array([[0, 0],
       [0, 0]], dtype=int8)

In [52]:
rref_binary(sm, False)

array([[1, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 1]], dtype=int8)