In [1]:
import pickle

import numpy as np

In [8]:
with open('data/3_qubit_stab_sorted.data', 'rb') as reader:
    stab_sorted = pickle.load(reader)

In [9]:
stab_matrix = np.loadtxt('data/3_qubit_matrix_sorted.csv', delimiter=',',
                         dtype=complex)

In [10]:
selection = stab_matrix[:, ::8]

In [11]:
stab_matrix[:, 560]

array([-0.5-0.j ,  0. -0.5j,  0. -0.j ,  0. -0.j ,  0. -0.j ,  0. -0.j ,
        0. -0.5j, -0.5-0.j ])

In [12]:
stab_sorted[560]

{'vector': array([[-0.5-0.j ],
        [ 0. -0.5j],
        [ 0. -0.j ],
        [ 0. -0.j ],
        [ 0. -0.j ],
        [ 0. -0.j ],
        [ 0. -0.5j],
        [-0.5-0.j ]]),
 'latex': '\\frac{1}{2}\\big{(}-|000\\rangle-i|001\\rangle-i|110\\rangle-|111\\rangle\\big{)}',
 'check_matrix': array([[1, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0]]),
 'generator_strs': ['XYZ', 'IZY', 'ZZI']}

In [13]:
stab_sorted[561]

{'vector': array([[-0. -0.j ],
        [-0. -0.j ],
        [ 0.5-0.j ],
        [-0. -0.5j],
        [-0. -0.5j],
        [ 0.5-0.j ],
        [-0. -0.j ],
        [-0. -0.j ]]),
 'latex': '\\frac{1}{2}\\big{(}|010\\rangle-i|011\\rangle-i|100\\rangle+|101\\rangle\\big{)}',
 'check_matrix': array([[1, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0]]),
 'generator_strs': ['XYZ', 'IZY', '-ZZI']}

In [14]:
n = 3
lin_dep_mat = np.loadtxt(f'data/{n}_qubit_nullspace_nice.csv', delimiter=',', dtype=complex)
updated_mat = (lin_dep_mat * np.sqrt(2)).round(3)

In [15]:
updated_mat[updated_mat == 1.414] = np.sqrt(2)

In [31]:
np.savetxt(f'data/{n}_qubit_B.csv', updated_mat, delimiter=',', fmt='%f')

------

In [2]:
n = 5
with open(f'data/{n}_qubit_subgroups.data', 'rb') as reader:
    check_matrices = pickle.load(reader)

In [4]:
def binary_matrix_rank(A):
    """
    Finds the rank of the binary matrix A by effectively converting it
    into row echelon form.

    Parameters
    ----------
    A : np.ndarray

    N.B. This method *changes* the matrix A!

    Returns
    -------
    rank : int
        The rank of matrix A.

    """

    num_rows, num_cols = A.shape
    rank = 0

    for j in range(num_cols):
        # Find the number of rows that have a 1 in the jth column
        rows = []
        for i in range(num_rows):
            if A[i, j] == 1:
                rows.append(i)

        # If the jth column has more than one 1, use row addition to
        # remove all 1s except the first one, then remove the first
        # such row and increase the rank by 1
        if len(rows) >= 1:
            for c in range(1, len(rows)):
                A[rows[c], :] = (A[rows[c], :] + A[rows[0], :]) % 2

            A = np.delete(A, rows[0], 0)
            num_rows -= 1
            rank += 1

    # For each remaining non-zero row in A, increase the rank by 1
    for row in A:
        if sum(row) > 0:
            rank += 1

    return rank

In [13]:
binary_matrix_rank(check_matrices[0][:, :n])

0

In [26]:
check_mats_sorted = sorted(check_matrices, 
                           key=lambda mat: binary_matrix_rank(mat[:, :n]))

In [27]:
check_mats_sorted[:10]

[array([[0, 1]]), array([[1, 0]]), array([[1, 1]])]

In [28]:
with open(f'data/{n}_qubit_subgroups.data', 'wb') as writer:
    pickle.dump(check_mats_sorted, writer)

In [2]:
def num_of_stab_states(n):
    return 2**n * np.prod(2**np.arange(1, n+1) + 1)

In [3]:
num_of_stab_states(5), num_of_stab_states(5) // 2**5

(2423520, 75735)

In [4]:
num_of_stab_states(6), num_of_stab_states(6) // 2**6

(315057600, 4922775)

------

In [2]:
import numpy as np
import scipy as sp
import scipy.sparse as spr

In [3]:
B_2 = spr.load_npz('data/2_qubit_B.npz')

In [8]:
nonzero_2 = []
for j in range(B_2.shape[1]):
    nonzero_2.append(B_2[:, j].nonzero()[0])

In [9]:
nonzero_2

[array([0, 1, 4], dtype=int32),
 array([2, 3, 5], dtype=int32),
 array([0, 1, 6], dtype=int32),
 array([2, 3, 7], dtype=int32),
 array([0, 1, 8], dtype=int32),
 array([2, 3, 9], dtype=int32),
 array([ 0,  1, 10], dtype=int32),
 array([ 2,  3, 11], dtype=int32),
 array([ 0,  2, 12], dtype=int32),
 array([ 1,  3, 13], dtype=int32),
 array([ 0,  2, 14], dtype=int32),
 array([ 1,  3, 15], dtype=int32),
 array([ 0,  2, 16], dtype=int32),
 array([ 1,  3, 17], dtype=int32),
 array([ 0,  2, 18], dtype=int32),
 array([ 1,  3, 19], dtype=int32),
 array([ 0,  3, 20], dtype=int32),
 array([ 1,  2, 21], dtype=int32),
 array([ 0,  3, 22], dtype=int32),
 array([ 1,  2, 23], dtype=int32),
 array([ 0,  3, 24], dtype=int32),
 array([ 1,  2, 25], dtype=int32),
 array([ 0,  3, 26], dtype=int32),
 array([ 1,  2, 27], dtype=int32),
 array([ 4,  5, 28], dtype=int32),
 array([ 6,  7, 29], dtype=int32),
 array([ 4,  5, 30], dtype=int32),
 array([ 6,  7, 31], dtype=int32),
 array([ 8,  9, 32], dtype=int32),
 ar