In [7]:
import pickle

import numpy as np

In [8]:
with open('data/3_qubit_stab_sorted.data', 'rb') as reader:
    stab_sorted = pickle.load(reader)

In [9]:
stab_matrix = np.loadtxt('data/3_qubit_matrix_sorted.csv', delimiter=',',
                         dtype=complex)

In [10]:
selection = stab_matrix[:, ::8]

In [11]:
stab_matrix[:, 560]

array([-0.5-0.j ,  0. -0.5j,  0. -0.j ,  0. -0.j ,  0. -0.j ,  0. -0.j ,
        0. -0.5j, -0.5-0.j ])

In [12]:
stab_sorted[560]

{'vector': array([[-0.5-0.j ],
        [ 0. -0.5j],
        [ 0. -0.j ],
        [ 0. -0.j ],
        [ 0. -0.j ],
        [ 0. -0.j ],
        [ 0. -0.5j],
        [-0.5-0.j ]]),
 'latex': '\\frac{1}{2}\\big{(}-|000\\rangle-i|001\\rangle-i|110\\rangle-|111\\rangle\\big{)}',
 'check_matrix': array([[1, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0]]),
 'generator_strs': ['XYZ', 'IZY', 'ZZI']}

In [13]:
stab_sorted[561]

{'vector': array([[-0. -0.j ],
        [-0. -0.j ],
        [ 0.5-0.j ],
        [-0. -0.5j],
        [-0. -0.5j],
        [ 0.5-0.j ],
        [-0. -0.j ],
        [-0. -0.j ]]),
 'latex': '\\frac{1}{2}\\big{(}|010\\rangle-i|011\\rangle-i|100\\rangle+|101\\rangle\\big{)}',
 'check_matrix': array([[1, 1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1, 1],
        [0, 0, 0, 1, 1, 0]]),
 'generator_strs': ['XYZ', 'IZY', '-ZZI']}

In [14]:
n = 3
lin_dep_mat = np.loadtxt(f'data/{n}_qubit_nullspace_nice.csv', delimiter=',', dtype=complex)
updated_mat = (lin_dep_mat * np.sqrt(2)).round(3)

In [15]:
updated_mat[updated_mat == 1.414] = np.sqrt(2)

In [31]:
np.savetxt(f'data/{n}_qubit_B.csv', updated_mat, delimiter=',', fmt='%f')

------

In [40]:
n = 4
with open(f'data/{n}_qubit_subgroups.data', 'rb') as reader:
    check_matrices = pickle.load(reader)

In [35]:
from subgroups import binary_matrix_rank

In [37]:
binary_matrix_rank(check_matrices[0][:, :4])

0

In [41]:
check_mats_sorted = sorted(check_matrices, 
                           key=lambda mat: binary_matrix_rank(mat[:, :4]))

In [42]:
check_mats_sorted[:10]

[array([[0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]]),
 array([[0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0]]),
 array([[0, 0, 0, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0]]),
 array([[0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]]),
 array([[0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]]),
 array([[0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1]]),
 array([[0, 0, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1]]),
 array([[0, 1, 0, 0, 0, 0, 0, 0],
